# Master pass
# dxrs-4apv-trin
version: '2'
services:
  web:
    image: matiascorvalan24/odoo14:20201112
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
      - ./config:/etc/odoo

    environment:
      - HOST=db

  db:
    image: postgres:10
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
